### ISSUE TITLE
Mobile - header section: Accordion arrow of the drop down menu is not in place.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#100]
Samsung S4,iTouch 5
![image](https://cloud.githubusercontent.com/assets/11186313/9489581/a85cf306-4c14-11e5-868c-be7f8e587637.png)

**Comment by roseliesromeo** [comment]
Not fixed in S4.

**Comment by ramoncebudigital** [comment]
clear cache, working on my end.
