### ISSUE TITLE
Mobile - header section: Second level drop down menu isn't styled accordingly.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#101]
Samsung S4 and iTouch 5
![image](https://cloud.githubusercontent.com/assets/11186313/9489614/d941f0ac-4c14-11e5-8965-275d344be05f.png)

**Comment by roseliesromeo** [comment]
Not fixed yet in S4.

**Comment by ramoncebudigital** [comment]
clear cache
