### ISSUE TITLE
Gallery page: Breadcrumbs layout and style isn't consistent with other pages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#104]
![image](https://cloud.githubusercontent.com/assets/11186313/9489895/cd618a16-4c16-11e5-8a9a-aa50ef7d9758.png)

**Comment by ramoncebudigital** [comment]
please specify the page

**Comment by roseliesromeo** [comment]
http://noordeman-responsive.stage.titanweb.com.au/gallery/nggallery/album-title-goes-here-for-two-lines-long/gallery
