### ISSUE TITLE
Gallery page: Bullet marks are displayed in the breadcrumbs.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#105]
![image](https://cloud.githubusercontent.com/assets/11186313/9489915/f35addda-4c16-11e5-826a-949187874669.png)

**Comment by ramoncebudigital** [comment]
please specify the page of this issue

**Comment by roseliesromeo** [comment]
http://noordeman-responsive.stage.titanweb.com.au/gallery/nggallery/album-title-goes-here-for-two-lines-long/gallery
