### ISSUE TITLE
Home page - featured products: There are 12 set featured products at back end but only 9 are displayed in front end.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#110]

**Comment by ramoncebudigital** [comment]
In the design, there are only 9 featured products

**Comment by roseliesromeo** [comment]
It is not specified in the scope to limit the number of featured image to display.  Itis even mentioned there to paginate after 9 featured products.

**Comment by ramoncebudigital** [comment]
The project scope was not updated, this is a project scope error.

**Comment by christiancebudigital** [comment]
Hi Roselie,

In project scope, Featured products was paginated if more than 9 but this was crossed out and was updated, so featured will only display 9 featured products.
https://docs.google.com/spreadsheets/d/1Fg9K018PjDxAKvIANFityo-LooGir-ZUlNk0-5hD9QA/edit?usp=sharing

Thanks,
Christian
