### ISSUE TITLE
General: Console error; Uncaught ReferenceError: analyticsEventTracking is not defined.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#12]
![image](https://cloud.githubusercontent.com/assets/11186313/9461485/a4f02464-4b41-11e5-9429-ec88c7d1cf8d.png)

**Comment by ramoncebudigital** [comment]
working on my end.
see screenshot
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/9709760/117313f4-5564-11e5-8fb0-943e0faf226c.png)

**Comment by roseliesromeo** [comment]
Other fixes may have affected this and fixed the issue.
