### ISSUE TITLE
Products single: Featured image and the image thumbnails are cut off.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#125]
As per Ricky's instruction in his email, product images should not be cropped.
![image](https://cloud.githubusercontent.com/assets/11186313/10301558/280d4b14-6c36-11e5-88c4-d68ff14f42ca.png)

![image](https://cloud.githubusercontent.com/assets/11186313/10301211/98ad7cbc-6c32-11e5-9453-4e73c092494a.png)

**Comment by christiancebudigital** [comment]
Hi Roselie,

I have a question, what if the images of the client, are not of the same size, just like this image 
http://noordeman-responsive.stage.titanweb.com.au/wp-content/uploads/2015/03/2656f853_Copy.jpg and 
http://noordeman-responsive.local.titanweb.com.au/wp-content/uploads/2012/08/2871a166.jpg
1 image have bigger height than others, do we only set a fixed width, and auto height just to make the image not to be cropped?

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

I think you miss out this line --

 "Please note that when you implement a woocommerce website, you need to set the wrapper of the image to be fixed width & height and then on the img tag you need to have max-width or max-height, 
This is to make sure all images blocks are the same size and images inside those blocks are fitted into the wrapper nicely. "

I believe it answers your question.

Thank you,
Seli

**Comment by roseliesromeo** [comment]
No fixes made.  
http://noordeman-responsive.stage.titanweb.com.au/products/alternators/test-product/

**Comment by christiancebudigital** [comment]
please clear cache

![aaaaa](https://cloud.githubusercontent.com/assets/11186331/10422584/d76d4962-70ee-11e5-918d-4088413485be.jpg)

**Comment by roseliesromeo** [comment]
Already cleared cache and still not fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/10424879/7bdcd8da-7105-11e5-874a-0fd14b8f6358.png)

**Comment by roseliesromeo** [comment]
Please apply fixes to home page - featured products.
![image](https://cloud.githubusercontent.com/assets/11186313/10447530/be8f0c72-71b7-11e5-8fd5-383c482eec3d.png)
