### ISSUE TITLE
Product listing page: Distorted layout of the page content.  There is no left padding and it doesn't utilize the entire screen for the page content.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#126]
S4, iTouch 5 
portrait view only
![image](https://cloud.githubusercontent.com/assets/11186313/10301818/b820d818-6c38-11e5-9368-b1a5c237ee15.png)

**Comment by christiancebudigital** [comment]
Hi Rosilie,

may i know, what page is this one?

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

It's the product listing page/category page. 
http://noordeman-responsive.stage.titanweb.com.au/product-category/perkins-engines-parts-and-products/
By the way it's not yet fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/10355634/f93adab0-6da0-11e5-9e4e-f92e115e66ef.png)

Thank you
