### ISSUE TITLE
Product listing page: Remove the border and drop shadow and follow design layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#129]
![image](https://cloud.githubusercontent.com/assets/11186313/10356026/f755bf04-6da4-11e5-9050-a5a5ce4703a1.png)

**Comment by christiancebudigital** [comment]
Hi Roselie,

This image is included on the uploaded image, only client can change this, since we dont have the actual product images, see link for the actual image [ http://noordeman-responsive.local.titanweb.com.au/wp-content/uploads/2012/08/2871a166-265x160.jpg ].

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

I can view the link added above.
