### ISSUE TITLE
Footer section: There are items in the footer menu that aren't supposed to be there per design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#13]
![image](https://cloud.githubusercontent.com/assets/11186313/9461643/7c684f3e-4b42-11e5-98c9-138b072b3fe7.png)

**Comment by ramoncebudigital** [comment]
existing in the current website http://www.noordeman.com.au/

**Comment by roseliesromeo** [comment]
There is no Workshop Tours in the top header of the existing website. It'd be redundant if we will keep it both in the top header and the footer menu.

**Comment by ramoncebudigital** [comment]
so, how about the "contact us" it is also on the top header and footer menu, i need to remove that also because it is redundant?

**Comment by ramoncebudigital** [comment]
how about the "contact us" isn't that redundant?
