### ISSUE TITLE
Footer section: Copy right text doesn't follow the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#14]
![image](https://cloud.githubusercontent.com/assets/11186313/9461673/b4c4150c-4b42-11e5-86bf-5f45cc71b121.png)

**Comment by ramoncebudigital** [comment]
same with this issue https://github.com/titan-cebu/Noordeman-Diesel/issues/13

**Comment by roseliesromeo** [comment]
Copyright text and footer menu are the same?
