### ISSUE TITLE
Video section:  There'll be no proper alignment if the video thumbnail is smaller.  There should be set width and height to maintain proper layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#25]
Currently, layout changes for every image size.
![image](https://cloud.githubusercontent.com/assets/11186313/9463387/0063bee8-4b4f-11e5-9769-3fdab8c7bcc7.png)

**Comment by ramoncebudigital** [comment]
updated the titan options thumbnail description.
