### ISSUE TITLE
Home page - featured products: It doesn't paginate after 9 products.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#26]
Currently, there are more than 10 featured products.  Only 9 are displayed and there is no pagination applied.
Per scope:
![image](https://cloud.githubusercontent.com/assets/11186313/9483339/8a2f821a-4bd1-11e5-9acd-906b1a6ea124.png)

**Comment by ramoncebudigital** [comment]
This is a project scope error. Featured products shouldn't have pagination.

**Comment by roseliesromeo** [comment]
Have the project scope updated.

**Comment by christiancebudigital** [comment]
Hi Rosilie,

Project scope have been, updated https://docs.google.com/spreadsheets/d/1Fg9K018PjDxAKvIANFityo-LooGir-ZUlNk0-5hD9QA/edit?usp=sharing.

Thanks,
Christian
