### ISSUE TITLE
Home page - featured products: Product description should have lowercase text transform as per design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#28]

**Comment by christiancebudigital** [comment]
Hi Roselie,

This an an existing content database which is found on this site, http://www.noordeman.com.au/, will wait for further clarifications, will flag this one as wont fix.

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Let's wait until this is clarified.

**Comment by roseliesromeo** [comment]
Has this been clarified?

**Comment by christiancebudigital** [comment]
Hi Roselie,

For all content that needs fixes, we dont need to touch it yet, since there is an existing site, we think these will be put to pre live fixes, since client will see the site first.

Thanks,
Christian
