### ISSUE TITLE
Cart page: We shouldn't be able to add products without price to Cart.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#29]
Add to Cart button shouldn't show or should be disabled for products without price. Ask assistance on how do this. Currently I can add products and can even proceed to checkout products without price.
![image](https://cloud.githubusercontent.com/assets/11186313/9483665/348dbf80-4bd5-11e5-898b-87c415f288bc.png)

![image](https://cloud.githubusercontent.com/assets/11186313/9485267/9688aef2-4be9-11e5-81f7-4506c19c0f38.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/10301584/774601e4-6c36-11e5-9618-1b56b168d43a.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

Updated theme file, if no regular price being inputted in backend, it will display in frontend "call a pricem" if inputted value of in reg price is z, this will display 'Price Not Announced' and will not display quatity box and add to cart, but if value on in reg price, is greater the 0, then it will display the quantity, as well as add to cart button, this is for us to control, on checking out items that will have upon checkout.

Thanks,
Christian
