### ISSUE TITLE
Profile page: Heading before the list of staffs should read "Staffs Profiles" instead of "Owners Profiles".

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#36]
Kindly refer to the web copy.
![image](https://cloud.githubusercontent.com/assets/11186313/9484121/9ca54034-4bda-11e5-92a2-50f0ff462d52.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
