### ISSUE TITLE
General: External link " Check out our New Online Perkins Parts store" is not part of the design and the approved web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#38]
![image](https://cloud.githubusercontent.com/assets/11186313/9484186/6c286dea-4bdb-11e5-842e-72f9e2a8ac1f.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
