### ISSUE TITLE
General: Pagination design layout and style is not consistent between blog and workshop tours page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#42]
Follow the design layout provided for the blog page.
![image](https://cloud.githubusercontent.com/assets/11186313/9484534/33356b64-4be0-11e5-82c2-26f209c31d28.png)

**Comment by ramoncebudigital** [comment]
duplicate https://github.com/titan-cebu/Noordeman-Diesel/issues/40

**Comment by roseliesromeo** [comment]
This is not duplicate to #40.  This is regarding the layout of the buttons used while #40 is about the button label that spills out.  They may have one fix but they are different issues.
