### ISSUE TITLE
Workshop single page:  There is no gallery acf created for each custom post. Only short code for certain workshop tours posts.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#45]
Per scope:
![image](https://cloud.githubusercontent.com/assets/11186313/9484682/07527ecc-4be2-11e5-93ff-f647943d92cc.png)

![image](https://cloud.githubusercontent.com/assets/11186313/9484698/349d7882-4be2-11e5-8786-d6e6685cbad6.png)

**Comment by ramoncebudigital** [comment]
This is a project scope error, project scope need to update. 
Existing website use NGG not gallery acf.
For more info please contact Christian.

**Comment by roseliesromeo** [comment]
Please have the project scope updated.

**Comment by christiancebudigital** [comment]
Hi Roselie,

Project scope have been updated, please see link below.
https://docs.google.com/spreadsheets/d/1Fg9K018PjDxAKvIANFityo-LooGir-ZUlNk0-5hD9QA/edit?usp=sharing

Thanks,
Christian

**Comment by roseliesromeo** [comment]
This is a valid issue. I'll mark this as won't fix instead since this is a scope error.
