### ISSUE TITLE
Workshop Tours: Page title should read "Workshop Tours". Lacking s

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#48]

**Comment by roseliesromeo** [comment]
Not fixed in the footer menu.

**Comment by ramoncebudigital** [comment]
refer to this issue: https://github.com/titan-cebu/Noordeman-Diesel/issues/13

**Comment by roseliesromeo** [comment]
Page title is now OK.  Why label this as invalid?
