### ISSUE TITLE
Products page: Style of the bullet marks in the listed content is different from the other pages. Applicable to News category page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#53]
Applicable to subcategory description.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-or-longer/subcategory-test-title-goes-here-for-two-lines-long-or-longer/
![image](https://cloud.githubusercontent.com/assets/11186313/9486102/65e1950a-4bf5-11e5-9894-27704b81f4c6.png)

**Comment by ramoncebudigital** [comment]
Invalid content added
![screenshot_3](https://cloud.githubusercontent.com/assets/11186436/9596012/821bf25a-50a1-11e5-8318-a5375e232218.png)

**Comment by roseliesromeo** [comment]
It's not an invalid content. It's the same content used in all pages but only in the subcategory page that the bullet marks are different.  It happens only after you created the subcategory and added description (using the same content).  Once you updated the description, the issue will be fixed. See http://noordeman-responsive.stage.titanweb.com.au/product-category/perkins-engines-parts-and-products/subcategory-test/

By the way, I am still able to replicate the issue. 
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-1/

**Comment by ramoncebudigital** [comment]
yeah, invalid content generated.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-1/
compare to this
http://noordeman-responsive.stage.titanweb.com.au/product-category/perkins-engines-parts-and-products/subcategory-test/

**Comment by roseliesromeo** [comment]
Still an Issue and it happens with newly created subcategory with newly added content.

**Comment by ramoncebudigital** [comment]
added new subcategory, try add content from MSWORD not copying from existing category content.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-5/

**Comment by roseliesromeo** [comment]
Not fixed.
I added new subcategory, added content from MSWORD not copying from existing category content.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-6/

Surely, this is not an invalid bug as I am able to replicate this over and over. 
![image](https://cloud.githubusercontent.com/assets/11186313/9957175/98127b32-5e30-11e5-84a1-d2e57dd4afb7.png)

**Comment by ramoncebudigital** [comment]
spot the difference
http://noordeman-responsive.local.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-6/

**Comment by roseliesromeo** [comment]
refer to bug #98.

**Comment by roseliesromeo** [comment]
Not fixed.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-8/

**Comment by christiancebudigital** [comment]
http://www.speakeasysolutions.com/blog/2011/05/24/pasting-options-in-ms-word-2010-eliminate-frustrations-associated-with-copying-from-another-source-and-pasting-in-ms-word/
and 
http://www.websighthangouts.com/how-to-paste-from-microsoft-word/

**Comment by roseliesromeo** [comment]
Still not fixed.  Style of bullet marks is still not consistent with other pages.

**Comment by christiancebudigital** [comment]
Hi Roselie,

Updated all the added content, NOTE: when copy pasting content, please paste it as text editor in wysiwyg, this is to avoid html tag generated in visual editor.

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

We copy and paste the content in the visual editor of the WYSIWYG like we normally do (with which have no issues with other projects).  With your way, we are not fixing the issue but avoiding it.  As much as possible we'd like to do things in the users perspective. And by the way, I am still able to replicate the problem. Kindly fix.

Thank you.

**Comment by christiancebudigital** [comment]
[10/5/2015 4:41:48 PM] Jo Erasmus: agreed and had a chat to Berns
[10/5/2015 4:42:40 PM] Jo Erasmus: and explained that we can not prevent user pasting styled content into the CMS, but that we do try to educate the client not to do it
