### ISSUE TITLE
Contact us page: Google map should initially be aligned with the message text box.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#65]
![image](https://cloud.githubusercontent.com/assets/11186313/9486730/92d75d62-4bfd-11e5-8bf6-e38bb9b4a78f.png)

**Comment by roseliesromeo** [comment]
Not fixed.

**Comment by ramoncebudigital** [comment]
clearly it went up, because the phone number is empty.

**Comment by roseliesromeo** [comment]
No change made.  Base of the message box and google map are still not aligned.
