### ISSUE TITLE
Contact us page: Lacking contact information as specified in the web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#68]
![image](https://cloud.githubusercontent.com/assets/11186313/9486824/afa00ad8-4bfe-11e5-809d-84a484e8412d.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
