### ISSUE TITLE
Crankshafts page: Page heading and body text is not updated as per the approved web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#72]
![image](https://cloud.githubusercontent.com/assets/11186313/9486959/fb043c0a-4bff-11e5-9ee7-ae109df1d6cc.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
