### ISSUE TITLE
Connecting Rods page: List of services doesn't match that of the web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#73]
![image](https://cloud.githubusercontent.com/assets/11186313/9486986/3e1ebbd2-4c00-11e5-8bab-23a73a9ca5f2.png)

The bottom link leads to an error page.

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
