### ISSUE TITLE
Genuine Parts page: Paragraph spacing is not consistent with other body contents.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#75]
http://noordeman-responsive.stage.titanweb.com.au/genuine-parts/
![image](https://cloud.githubusercontent.com/assets/11186313/9487074/34f88460-4c01-11e5-929a-e5628081d78c.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
We won't touch the actual content.  But at least apply proper styling and layout for consistency.  At least make it presentable to the client.

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by bernardtitan** [comment]
This doesn't answer the issue at all

**Comment by bernardtitan** [comment]
Upon further investigation, the ordered lists weren't set properly, causing the spacing issue. Someone fixed it the day after Ramon's comment, thus the label is changed to fixed. 

Don't dismiss all content issues outright, as backtracking is also a waste of my time.
