### ISSUE TITLE
Genuine Parts page: Listed contents don't have bullet marks.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#76]
http://noordeman-responsive.stage.titanweb.com.au/genuine-parts/
![image](https://cloud.githubusercontent.com/assets/11186313/9487066/23ce5caa-4c01-11e5-9950-4d42e26bcaa5.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
We won't touch the actual content.  But at least apply proper styling and layout for consistency.  At least make it presentable to the client.

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
Comment is not relevant to this issue.
I've asked Bernard and he agreed to have the proper layout and style applied for web to look pleasant at least.
