### ISSUE TITLE
Spare Parts page: Body content is not updated as per the approved web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#77]
Applicable to the whole body content.
![image](https://cloud.githubusercontent.com/assets/11186313/9487119/8c0165e2-4c01-11e5-8d79-fd37dd73ae2d.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
