### ISSUE TITLE
Spare Parts page: Area code of the phone and fax numbers are not enclosed in parentheses.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#78]
![image](https://cloud.githubusercontent.com/assets/11186313/9487151/bc78f668-4c01-11e5-8a4b-8944472a35bb.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
I guess adding parentheses won't change the meaning. It will be just the same phone number. We will just adhere to the standard.

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
That is not relevant to the issue.
I've consulted Bernard regarding this and he agreed to have the standard format of phone applied here.
