### ISSUE TITLE
Spare Parts page: Email is supposed to be linked to an email platform.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#79]
![image](https://cloud.githubusercontent.com/assets/11186313/9487176/da48a8aa-4c01-11e5-947f-958ed071f623.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
We won't touch/change/modify the actual content but at least make the items in it work and maintain proper styling and layout.

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.

**Comment by roseliesromeo** [comment]
That doesn't apply to this issue.  
I've asked Bernard and he agreed to make links work properly and make the layout look pleasant at least.
