### ISSUE TITLE
New Engine page: Link to Engine Inquiry Form isn't part of the content per web copy.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#81]
![image](https://cloud.githubusercontent.com/assets/11186313/9487319/08e82892-4c03-11e5-97e8-a51d3690b50c.png)

**Comment by ramoncebudigital** [comment]
This is from jolene, "Bernard can you please let the QA tester know not to worry about the actual content as part of the QA process." this will be labeled as wont fix. please consult with bernard if you have question Thanks.
