### ISSUE TITLE
Blog single page: Featured image is not left aligned.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#88]
![image](https://cloud.githubusercontent.com/assets/11186313/9487781/7f8ca4f6-4c07-11e5-96a1-6be967d32628.png)

**Comment by ramoncebudigital** [comment]
This is not a featured image, this image is a NGG added by client.
same issue this https://github.com/titan-cebu/Noordeman-Diesel/issues/89

**Comment by roseliesromeo** [comment]
NGG/featured image should aligned to maintain layout/alignment.
