### ISSUE TITLE
Product subcategory page: Listed content displays the codes. Applicable to News category page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Noordeman-Diesel#98]
IE9 - http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-or-longer/subcategory-test-title-goes-here-for-two-lines-long-or-longer/
Same content looks good in the rest of the browsers.
![image](https://cloud.githubusercontent.com/assets/11186313/9489195/c3d7291a-4c11-11e5-92cb-f6681cb4ff56.png)

**Comment by roseliesromeo** [comment]
Fix has not been applied in IE9 yet
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-1/

Steps:
1. Create subcategory
2. Add testing sample content

![image](https://cloud.githubusercontent.com/assets/11186313/9752677/a27e7cc6-56e5-11e5-95e6-844687a666c8.png)

**Comment by ramoncebudigital** [comment]
re-add the content. it wasn't generated properly.

**Comment by roseliesromeo** [comment]
Issue is still there for newly created subcategory and newly added content. It will display properly once you updated the content.

Issue exists in IE9
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-4/

**Comment by ramoncebudigital** [comment]
added new subcategory
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-5/

**Comment by roseliesromeo** [comment]
not fixed.
I added new subcategory, added content from MSWORD not copying from existing category content.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-6/

Surely this is not an invalid bug as I am able to replicate this over and over.

**Comment by ramoncebudigital** [comment]
spot the difference.
http://noordeman-responsive.local.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-6/

**Comment by roseliesromeo** [comment]
1. I can't view the local link you included in the comment.
2. I am not sure how you added the content, but I am still able to replicate the same issue by doing the usual way of adding content to pages.
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-7/
3. Like I commented above, this issue occurs if you added content in the description field right when creating the category, not editing after you created it.

How did you insert the content by the way?
Notice that when added the content right when you create a category, the letters in the list remain as they are.  But when you try to edit the category and paste the same content, the letters in the list are automatically replaced by numbers.  That is the difference that you needs fixing.

![image](https://cloud.githubusercontent.com/assets/11186313/10037105/0a46866a-61e4-11e5-8374-5f3b0fb518fa.png)

**Comment by christiancebudigital** [comment]
Hi Roselie,

It Seems that the text pasted on the category description, is encoded with added code,
see difference on this links:

http://noordeman-responsive.local.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-test-6/ - working
http://noordeman-responsive.stage.titanweb.com.au/product-category/test-category-test-title-goes-here-for-two-lines-long-and-longer/subcategory-7/ - endoded text

see attached images too:
![encoded text](https://cloud.githubusercontent.com/assets/11186331/10154036/1fffc8ee-6695-11e5-94e3-8d5d904c30ff.jpg)

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

There is no added code in the content.  The content added in this page is the same content added to all other pages and the issue exists in the category/subcategory page and in IE9 only.  The codes won't display in all other browsers only that the bullet marks have different style.

You can even replicate it on your end if you follow these steps.
1. Create a new product category/subcategory at back end. Go to Admin - Product categories
2. Copy the contents in the attach doc. below and paste it in the description field.
3. Click Add New Product Category button.

[Sample Content.docx](https://github.com/titan-cebu/Noordeman-Diesel/files/4111/Sample.Content.docx)

Notice that when you added the content right when you create a category, the letters in the list remain as they are. But when you try to edit the category and paste the same content, the letters in the list are automatically replaced by numbers. The problem is with the editor when you created the category.

**Comment by christiancebudigital** [comment]
Hi Erma,

It seems to be working fine on our end, following your steps, see attached files
![a](https://cloud.githubusercontent.com/assets/11186331/10186627/1e23160c-6785-11e5-8f15-8f233a2b4c45.jpg)
![b](https://cloud.githubusercontent.com/assets/11186331/10186628/1e4dd81a-6785-11e5-966b-e9ea37667122.jpg)

maybe its the default copy pasting of your word..  
see this links for your info
http://www.speakeasysolutions.com/blog/2011/05/24/pasting-options-in-ms-word-2010-eliminate-frustrations-associated-with-copying-from-another-source-and-pasting-in-ms-word/
and
http://www.websighthangouts.com/how-to-paste-from-microsoft-word/

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Issue not fixed.  Same issue in IE9

**Comment by christiancebudigital** [comment]
Hi Roselie,

Updated all the added content, NOTE: when copy pasting content, please paste it as text editor in wysiwyg, this is to avoid html tag generated in visual editor.

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi Christian,

We copy and paste the content in the visual editor of the WYSIWYG like we normally do (with which have no issues with other projects).  With your way, we are not fixing the issue but avoiding it.  As much as possible we'd like to do things in the users perspective. And by the way, I am still able to replicate the problem. Kindly fix.

Thank you.

**Comment by christiancebudigital** [comment]
[10/5/2015 4:41:48 PM] Jo Erasmus: agreed and had a chat to Berns
[10/5/2015 4:42:40 PM] Jo Erasmus: and explained that we can not prevent user pasting styled content into the CMS, but that we do try to educate the client not to do it
